### ISSUE TITLE
Map explorer - display more thumbnails at one time

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/mbaza#177]
Make more images visible at any one time to speed up tagging and reduce scrolling. Note that high resolution images are currently loaded full size and significantly slow down the app.

Here are some screenshots from a similar app that classifies animals and is then used for validation:
![WhatsApp Image 2021-07-21 at 15 35 21](https://user-images.githubusercontent.com/10000651/135979654-219a6676-b746-4233-a598-ac261296e94b.jpeg)
![WhatsApp Image 2021-07-21 at 15 35 22](https://user-images.githubusercontent.com/10000651/135979657-6058c21f-32ac-4603-aa0f-48cd49776282.jpeg)
![WhatsApp Image 2021-07-21 at 15 38 45](https://user-images.githubusercontent.com/10000651/135979660-cb68d63d-c0f2-4b7e-a0d6-d347a2eab593.jpeg)

**Comment by jchojna** [comment]
[Figma Prototype](https://www.figma.com/proto/cink8VlWvTley84xJp8S0i/Mbaza?node-id=565%3A214882&viewport=514%2C480%2C0.18&scaling=contain&page-id=565%3A214881&starting-point-node-id=565%3A217188)

**Comment by jchojna** [comment]
**Implementation Plan:**

- [ ] move observations panel to cover the map component
- [ ] create observations box's header with title and back button
- [ ] create grid of cards
- [ ] change card element according to the mockup
- [ ] display information on card's hover
- [ ] add functionality to maximize a card
- [ ] handle 'back to observations' button
- [ ] ...
