### ISSUE TITLE
Improve map explorer performance

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/mbaza#184]
Display a maximum number of images that display per page when viewing images on a camera station. Currently if one camera station has 1000s of images I think the app tries to load them all into one page, which makes it very slow

**Comment by jchojna** [comment]
To increase the speed of loading the observations list component, which can have a huge list of DOM elements to append, one of the best solutions may be `virtualization`. There is a popular package for react - [react-window](https://github.com/bvaughn/react-window) which seems to be worth trying. Here is one of the [tutorials](https://blog.openreplay.com/virtualizing-large-data-lists-with-react-window).

**Comment by jchojna** [comment]
**Implementation Plan:**

- [ ] install `react-window` and `react-window-infinite-loader`
- [ ] experiment with some example app of react-window inside mbaza
- [ ] use `InfiniteLoader` and `FixedSizeList` components from react-window
- [ ] pass `ObservationCard` mbaza's component as a child of `FixedSizeList` react-window's component
- [ ] pass `observations` data as an argument of FixedSizeList (itemData parameter)
- [ ] handle observations data using `FixedSizeList` child's index
- [ ] add all typescript's typings
- [ ] maybe slightly change appearance of observations cards on scroll, to make scrolling more smooth (react-window has api for it)
- [ ] refactor
