### ISSUE TITLE
Adjust UI for implementing Events functionality

### ISSUE THREAD

**Issue by jchojna** [Appsilon/mbaza#207]
New UI changes should be based on Option B of design proposals introduced in this [task](https://github.com/Appsilon/mbaza/issues/197)

**Implementation Plan:**

- [x] display overrides value in a separate metric tile
- [x] display events amount in a separate metric tile
- [x] display loaded csv file in upper left corner as a text output
- [x] change import / export buttons appearance
- [x] add 'Update events' button
- [x] move all buttons to upper right corner
- [x] adjust layout of metrics, filters and slider element
- [x] add popup element for updating events
- [x] change initial look of explore page to include input element with csv file, ok button and button to show additional information
- [x] display additional information when hovering over help button
- [x] add simple background as svg graphic
- [x] integrate events functionality
