### ISSUE TITLE
Consistently use one technique to add styling

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/mbaza#237]
We have a mix of inline styles, CSS and Sass modules. We should pick one approach and ensure the project consistently uses it. In particular, we should (probably) get rid of inline styles.

**Implementation Plan:**

- [x] use PascalCase everywhere to name components files
- [x] import scss modules as `styles` everywhere
- [x] use camelCase when defining scss modules classes
- [x] move inline styles to scss modules
- [x] use @use to import sass modules instead of @import 
- [x] remove app.global.css
- [x] refactor global scss modules
