### ISSUE TITLE
Override predictions for multiple photos in one go

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/mbaza#300]
1. The user can enter “selection mode” by clicking a check icon in the top left corner of the photo (appears on hover).
2. In selection mode, the whole header of the observation inspector changes to display information about the selection and tools:
    1. A cross icon on the left to exit the selection mode.
    2. “N photos selected” title.
    3. On the right there is an “Override” dropdown and “Update” confirmation button.

**Comment by jchojna** [comment]
**Implementation Plan:**

- [ ] add check icon button to the top left corner
- [ ] handle card appearance change on the icon button click
- [ ] activate multiselection mode on icon button click
- [ ] change appearance of box header on icon button click
- [ ] handle multiselect mode cancellation
- [ ] display how many cards selected
- [ ] add dropdown element to the right side of box header
- [ ] add Confirm button overriding predictions in selected cards
