### ISSUE TITLE
Easily navigate to next/previous image in the map explorer

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/mbaza#302]
**Implementation Plan:**

- [x] add left and right arrows
- [x] add switch functionality
- [x] add counter / current observation
- [x] add sliding transition
- [x] add keyboard shortcuts (left/right/esc)
- [x] fix {{current}} in map popup
- [x] refactor / small fixes
